version: "3.8"
services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0-slim
    container_name: oracle21xe
    environment:
      ORACLE_PASSWORD: "123"
      ORACLE_CHARACTERSET: "AL32UTF8"
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:

