# Generated by Django 5.1.2 on 2026-08-28 21:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("sifra_k", models.AutoField(primary_key=True, serialize=False)),
                ("ime_k", models.CharField(max_length=50)),
                ("prz_k", models.CharField(max_length=50)),
                ("mail_k", models.EmailField(max_length=100, unique=True)),
                (
                    "tip_k",
                    models.CharField(
                        choices=[
                            ("logisticki_koordinator", "Logistički koordinator"),
                            ("skladisni_operater", "Skladišni operater"),
                            ("nabavni_menadzer", "Nabavni menadžer"),
                            ("finansijski_analiticar", "Finansijski analitičar"),
                            ("kontrolor_kvaliteta", "Kontrolor kvaliteta"),
                            ("administrator", "Administrator"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "korisnik",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Artikal",
            fields=[
                ("sifra_a", models.AutoField(primary_key=True, serialize=False)),
                ("naziv_a", models.CharField(max_length=150)),
                (
                    "osnovna_cena_a",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("rok_trajanja_a", models.DateField()),
                (
                    "status_trajanja_a",
                    models.CharField(
                        choices=[
                            ("aktivan", "Aktivan"),
                            ("istice", "Uskoro ističe"),
                            ("istekao", "Istekao"),
                        ],
                        default="aktivan",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "db_table": "artikal",
            },
        ),
        migrations.CreateModel(
            name="Dobavljac",
            fields=[
                ("sifra_db", models.AutoField(primary_key=True, serialize=False)),
                ("naziv_db", models.CharField(max_length=150)),
                ("email_db", models.EmailField(max_length=100)),
                ("pib_db", models.CharField(max_length=20, unique=True)),
                (
                    "ocena_db",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                    ),
                ),
                ("datum_ocenjivanja", models.DateField()),
                ("ime_sirovine", models.CharField(max_length=200)),
                ("cena", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rok_isporuke",
                    models.IntegerField(help_text="Rok isporuke u danima"),
                ),
                ("izabran", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dobavljac",
            },
        ),
        migrations.CreateModel(
            name="JedinicaMere",
            fields=[
                ("sifra_jm", models.AutoField(primary_key=True, serialize=False)),
                ("naziv_jm", models.CharField(max_length=100)),
                ("oznaka_jm", models.CharField(max_length=20)),
                (
                    "tip_jm",
                    models.CharField(
                        choices=[
                            ("KOLICINA", "Količina"),
                            ("MASA", "Masa"),
                            ("ZAPREMINA", "Zapremina"),
                            ("NOVAC", "Novac"),
                            ("PROCENAT", "Procenat"),
                            ("VREME", "Vreme"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "jedinica_mere",
            },
        ),
        migrations.CreateModel(
            name="KategorijaProizvoda",
            fields=[
                ("sifra_kp", models.AutoField(primary_key=True, serialize=False)),
                ("naziv_kp", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "kategorija_proizvoda",
            },
        ),
        migrations.CreateModel(
            name="KontrolnaTabla",
            fields=[
                ("sifra_kt", models.AutoField(primary_key=True, serialize=False)),
                ("naziv_kt", models.CharField(max_length=150)),
                ("opis_kt", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "db_table": "kontrolna_tabla",
            },
        ),
        migrations.CreateModel(
            name="Notifikacija",
            fields=[
                ("sifra_n", models.AutoField(primary_key=True, serialize=False)),
                ("poruka_n", models.CharField(max_length=1000)),
                ("datum_n", models.DateTimeField(auto_now_add=True)),
                ("procitana_n", models.BooleanField(default=False)),
                ("link_n", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "db_table": "notifikacija",
                "ordering": ["-datum_n"],
            },
        ),
        migrations.CreateModel(
            name="Popust",
            fields=[
                ("sifra_pop", models.AutoField(primary_key=True, serialize=False)),
                ("pred_cena_pop", models.DecimalField(decimal_places=2, max_digits=12)),
                ("datum_poc_vaz_pop", models.DateField()),
                ("datum_kr_vaz_pop", models.DateField()),
            ],
            options={
                "db_table": "popust",
            },
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                ("sifra_r", models.AutoField(primary_key=True, serialize=False)),
                ("polazna_tacka", models.CharField(max_length=100)),
                ("odrediste", models.CharField(max_length=100)),
                ("duzina_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vreme_dolaska", models.DurationField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planirana", "Planirana"),
                            ("zavrsena", "Zavrsena"),
                            ("u_toku", "U toku"),
                            ("odstupanje", "Odstupanje od pocetne rute"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "ruta",
            },
        ),
        migrations.CreateModel(
            name="Skladiste",
            fields=[
                ("sifra_sk", models.AutoField(primary_key=True, serialize=False)),
                ("mesto_sk", models.CharField(max_length=150)),
                (
                    "status_rizika_sk",
                    models.CharField(
                        choices=[
                            ("nizak", "Nizak rizik"),
                            ("umeren", "Umeren rizik"),
                            ("visok", "Visok rizik"),
                        ],
                        default="nizak",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "db_table": "skladiste",
            },
        ),
        migrations.CreateModel(
            name="Vozac",
            fields=[
                ("sifra_vo", models.AutoField(primary_key=True, serialize=False)),
                ("ime_vo", models.CharField(max_length=100)),
                ("prz_vo", models.CharField(max_length=100)),
                ("br_voznji", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("slobodan", "Slobodan"),
                            ("zauzet", "Zauzet"),
                            ("na_odmoru", "Na odmoru"),
                        ],
                        default="slobodan",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "vozac",
            },
        ),
        migrations.CreateModel(
            name="Vozilo",
            fields=[
                ("sifra_v", models.AutoField(primary_key=True, serialize=False)),
                ("marka", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("registracija", models.DateField(blank=True)),
                ("kapacitet", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("zauzeto", "Zauzeto"),
                            ("slobodno", "Slobodno"),
                            ("u_kvaru", "U kvaru"),
                            ("na_servisu", "Na servisu"),
                        ],
                        default="aktivno",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "vozilo",
            },
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "korisnik",
                    models.OneToOneField(
                        db_column="sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="administrator",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "administrator",
            },
        ),
        migrations.CreateModel(
            name="FinansijskiAnaliticar",
            fields=[
                (
                    "korisnik",
                    models.OneToOneField(
                        db_column="sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="finansijski_analiticar",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finansijski_analiticar",
            },
        ),
        migrations.CreateModel(
            name="KontrolorKvaliteta",
            fields=[
                (
                    "korisnik",
                    models.OneToOneField(
                        db_column="sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="kontrolor_kvaliteta",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "kontrolor_kvaliteta",
            },
        ),
        migrations.CreateModel(
            name="LogistickiKoordinator",
            fields=[
                (
                    "korisnik",
                    models.OneToOneField(
                        db_column="sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="logisticki_koordinator",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "logisticki_koordinator",
            },
        ),
        migrations.CreateModel(
            name="NabavniMenadzer",
            fields=[
                (
                    "korisnik",
                    models.OneToOneField(
                        db_column="sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="nabavni_menadzer",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nabavni_menadzer",
            },
        ),
        migrations.CreateModel(
            name="SkladisniOperater",
            fields=[
                (
                    "korisnik",
                    models.OneToOneField(
                        db_column="sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="skladisni_operater",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "skladisni_operater",
            },
        ),
        migrations.CreateModel(
            name="Faktura",
            fields=[
                ("sifra_f", models.AutoField(primary_key=True, serialize=False)),
                ("iznos_f", models.DecimalField(decimal_places=2, max_digits=12)),
                ("datum_prijema_f", models.DateField()),
                ("rok_placanja_f", models.DateField()),
                (
                    "status_f",
                    models.CharField(
                        choices=[
                            ("primljena", "Primljena"),
                            ("verifikovana", "Verifikovana"),
                            ("isplacena", "Isplaćena"),
                            ("odbijena", "Odbijena"),
                        ],
                        default="primljena",
                        max_length=30,
                    ),
                ),
                (
                    "valuta",
                    models.ForeignKey(
                        db_column="JEDINICA_MERE_sifra_jm",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fakture",
                        to="app.jedinicamere",
                    ),
                ),
            ],
            options={
                "db_table": "faktura",
            },
        ),
        migrations.CreateModel(
            name="Kreiranje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum_kr", models.DateTimeField(auto_now_add=True)),
                (
                    "kontrolna_tabla",
                    models.ForeignKey(
                        db_column="KONTROLNA_TABLA_sifra_kt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.kontrolnatabla",
                    ),
                ),
                (
                    "finansijski_analiticar",
                    models.ForeignKey(
                        db_column="FINANSIJSKI_ANALITICAR_sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.finansijskianaliticar",
                    ),
                ),
            ],
            options={
                "db_table": "kreiranje",
            },
        ),
        migrations.CreateModel(
            name="Merenje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vrednost_me", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "vreme_merenja_me",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("period_od_me", models.DateField(blank=True, null=True)),
                ("period_do_me", models.DateField(blank=True, null=True)),
                (
                    "kontrolna_tabla",
                    models.ForeignKey(
                        db_column="KONTROLNA_TABLA_sifra_kt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merenja",
                        to="app.kontrolnatabla",
                    ),
                ),
            ],
            options={
                "db_table": "merenje",
            },
        ),
        migrations.CreateModel(
            name="Izvestaj",
            fields=[
                ("sifra_i", models.AutoField(primary_key=True, serialize=False)),
                ("datum_i", models.DateTimeField(auto_now_add=True)),
                (
                    "tip_i",
                    models.CharField(
                        choices=[
                            ("FINANSIJSKI", "Finansijski"),
                            ("DOBAVLJACI", "Dobavljači"),
                            ("UGOVORI", "Ugovori"),
                            ("PLACANJA", "Plaćanja"),
                        ],
                        max_length=30,
                    ),
                ),
                ("period_od_i", models.DateField(blank=True, null=True)),
                ("period_do_i", models.DateField(blank=True, null=True)),
                (
                    "pdf_fajl",
                    models.FileField(
                        blank=True, null=True, upload_to="izvestaji_pdfs/"
                    ),
                ),
                (
                    "kreiranje",
                    models.ForeignKey(
                        db_column="KREIRANJE_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="izvestaji",
                        to="app.kreiranje",
                    ),
                ),
                (
                    "merenja",
                    models.ManyToManyField(
                        blank=True, related_name="izvestaji", to="app.merenje"
                    ),
                ),
            ],
            options={
                "db_table": "izvestaj",
            },
        ),
        migrations.CreateModel(
            name="Metrika",
            fields=[
                ("sifra_m", models.AutoField(primary_key=True, serialize=False)),
                ("naziv_m", models.CharField(max_length=150)),
                ("opis_m", models.CharField(blank=True, max_length=500)),
                ("formula_m", models.CharField(blank=True, max_length=500)),
                (
                    "jedinica_mere",
                    models.ForeignKey(
                        db_column="JEDINICA_MERE_sifra_jm",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metrike",
                        to="app.jedinicamere",
                    ),
                ),
            ],
            options={
                "db_table": "metrika",
            },
        ),
        migrations.AddField(
            model_name="merenje",
            name="metrika",
            field=models.ForeignKey(
                db_column="METRIKA_sifra_m",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merenja",
                to="app.metrika",
            ),
        ),
        migrations.CreateModel(
            name="OcenaDobavljaca",
            fields=[
                ("sifra_od", models.AutoField(primary_key=True, serialize=False)),
                (
                    "kriterijum_od",
                    models.CharField(
                        choices=[
                            ("TACNOST_FAKTURISANJA", "Tačnost fakturisanja"),
                            ("POSTOVANJE_ROKOVA", "Poštovanje rokova"),
                            ("BROJ_PENALA", "Broj penala"),
                            ("ODNOS_CENA", "Odnos cena"),
                        ],
                        max_length=30,
                    ),
                ),
                ("vrednost_od", models.DecimalField(decimal_places=2, max_digits=5)),
                ("period_od_od", models.DateField()),
                ("period_do_od", models.DateField()),
                ("datum_ocenj_od", models.DateField()),
                (
                    "dobavljac",
                    models.ForeignKey(
                        db_column="DOBAVLJAC_sifra_db",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocene",
                        to="app.dobavljac",
                    ),
                ),
            ],
            options={
                "db_table": "ocena_dobavljaca",
            },
        ),
        migrations.CreateModel(
            name="Proizvod",
            fields=[
                ("sifra_pr", models.AutoField(primary_key=True, serialize=False)),
                ("naziv_pr", models.CharField(max_length=150)),
                ("opis_pr", models.TextField(blank=True)),
                (
                    "pdv_stopa_pr",
                    models.IntegerField(
                        choices=[(0, "0%"), (10, "10%"), (20, "20%")], default=20
                    ),
                ),
                (
                    "jedinica_mere",
                    models.ForeignKey(
                        db_column="JEDINICA_MERE_sifra_jm",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proizvodi",
                        to="app.jedinicamere",
                    ),
                ),
                (
                    "kategorija",
                    models.ForeignKey(
                        db_column="KATEGORIJA_PROIZVODA_sifra_kp",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proizvodi",
                        to="app.kategorijaproizvoda",
                    ),
                ),
            ],
            options={
                "db_table": "proizvod",
            },
        ),
        migrations.CreateModel(
            name="ProizvodDobavljaca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sifra_kod_dobavljaca_pd",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dobavljac",
                    models.ForeignKey(
                        db_column="DOBAVLJAC_sifra_db",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="katalog",
                        to="app.dobavljac",
                    ),
                ),
                (
                    "proizvod",
                    models.ForeignKey(
                        db_column="PROIZVOD_sifra_pr",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ponude_dobavljaca",
                        to="app.proizvod",
                    ),
                ),
            ],
            options={
                "db_table": "proizvod_dobavljaca",
            },
        ),
        migrations.CreateModel(
            name="Cenovnik",
            fields=[
                ("sifra_c", models.AutoField(primary_key=True, serialize=False)),
                ("cena_c", models.DecimalField(decimal_places=2, max_digits=12)),
                ("datum_od_c", models.DateField()),
                (
                    "datum_do_c",
                    models.DateField(
                        blank=True, help_text="NULL = trenutno važeća cena", null=True
                    ),
                ),
                (
                    "valuta",
                    models.ForeignKey(
                        db_column="JEDINICA_MERE_sifra_jm",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cene",
                        to="app.jedinicamere",
                    ),
                ),
                (
                    "proizvod_dobavljaca",
                    models.ForeignKey(
                        db_column="PROIZVOD_DOBAVLJACA_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cenovnik",
                        to="app.proizvoddobavljaca",
                    ),
                ),
            ],
            options={
                "db_table": "cenovnik",
            },
        ),
        migrations.CreateModel(
            name="PromenaStatusa",
            fields=[
                ("sifra_ps", models.AutoField(primary_key=True, serialize=False)),
                ("datum_vreme_ps", models.DateTimeField(auto_now_add=True)),
                (
                    "stari_status_ps",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primljena", "Primljena"),
                            ("verifikovana", "Verifikovana"),
                            ("isplacena", "Isplaćena"),
                            ("odbijena", "Odbijena"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "novi_status_ps",
                    models.CharField(
                        choices=[
                            ("primljena", "Primljena"),
                            ("verifikovana", "Verifikovana"),
                            ("isplacena", "Isplaćena"),
                            ("odbijena", "Odbijena"),
                        ],
                        max_length=30,
                    ),
                ),
                ("razlog_ps", models.CharField(blank=True, max_length=500)),
                (
                    "faktura",
                    models.ForeignKey(
                        db_column="FAKTURA_sifra_f",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promene_statusa",
                        to="app.faktura",
                    ),
                ),
                (
                    "korisnik",
                    models.ForeignKey(
                        db_column="KORISNIK_sifra_k",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promene_statusa_izvrsene",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promena_statusa",
                "ordering": ["-datum_vreme_ps"],
            },
        ),
        migrations.CreateModel(
            name="Isporuka",
            fields=[
                ("sifra_i", models.AutoField(primary_key=True, serialize=False)),
                ("kolicina_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktivna", "Nova"),
                            ("u_toku", "U toku"),
                            ("spremna", "Spremna"),
                            ("zavrsena", "Završena"),
                        ],
                        default="aktivna",
                        max_length=20,
                    ),
                ),
                ("datum_kreiranja", models.DateTimeField(auto_now_add=True)),
                ("datum_polaska", models.DateTimeField(blank=True, null=True)),
                ("rok_is", models.DateTimeField(blank=True, null=True)),
                ("datum_dolaska", models.DateTimeField(blank=True, null=True)),
                (
                    "ruta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ruta",
                    ),
                ),
                (
                    "vozac",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.vozac",
                    ),
                ),
                (
                    "vozilo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.vozilo",
                    ),
                ),
            ],
            options={
                "db_table": "isporuka",
            },
        ),
        migrations.CreateModel(
            name="SePrimenjuje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_pi",
                    models.CharField(
                        choices=[("aktivan", "Aktivan"), ("istekao", "Istekao")],
                        default="aktivan",
                        max_length=30,
                    ),
                ),
                (
                    "artikal",
                    models.ForeignKey(
                        db_column="ARTIKAL_sifra_a",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.artikal",
                    ),
                ),
                (
                    "popust",
                    models.ForeignKey(
                        db_column="POPUST_sifra_pop",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.popust",
                    ),
                ),
            ],
            options={
                "db_table": "se_primenjuje",
            },
        ),
        migrations.AddField(
            model_name="popust",
            name="artikli",
            field=models.ManyToManyField(
                blank=True,
                related_name="popusti",
                through="app.SePrimenjuje",
                to="app.artikal",
            ),
        ),
        migrations.CreateModel(
            name="Sertifikat",
            fields=[
                ("sifra_s", models.AutoField(primary_key=True, serialize=False)),
                ("naziv_s", models.CharField(max_length=150)),
                (
                    "tip_s",
                    models.CharField(
                        choices=[
                            ("ISO", "ISO"),
                            ("HACCP", "HACCP"),
                            ("GMP", "GMP"),
                            ("BRC", "BRC"),
                            ("IFS", "IFS"),
                            ("ostalo", "Ostalo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("datum_izdavanja_s", models.DateField()),
                ("aktuelno_s", models.BooleanField(default=True)),
                ("datum_isteka_s", models.DateField()),
                (
                    "dobavljac",
                    models.ForeignKey(
                        db_column="DOBAVLJAC_sifra_db",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sertifikati",
                        to="app.dobavljac",
                    ),
                ),
            ],
            options={
                "db_table": "sertifikat",
            },
        ),
        migrations.CreateModel(
            name="SeSalje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "korisnik",
                    models.ForeignKey(
                        db_column="KORISNIK_sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notifikacija",
                    models.ForeignKey(
                        db_column="NOTIFIKACIJA_sifra_n",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.notifikacija",
                    ),
                ),
            ],
            options={
                "db_table": "se_salje",
            },
        ),
        migrations.AddField(
            model_name="notifikacija",
            name="korisnici",
            field=models.ManyToManyField(
                blank=True,
                related_name="notifikacije",
                through="app.SeSalje",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StavkaFakture",
            fields=[
                ("sifra_sf", models.AutoField(primary_key=True, serialize=False)),
                ("naziv_sf", models.CharField(max_length=150)),
                (
                    "kolicina_sf",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "cena_po_jed_sf",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("opis_sf", models.CharField(blank=True, max_length=1000)),
                (
                    "faktura",
                    models.ForeignKey(
                        db_column="FAKTURA_sifra_f",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stavke",
                        to="app.faktura",
                    ),
                ),
                (
                    "proizvod_dobavljaca",
                    models.ForeignKey(
                        db_column="PROIZVOD_DOBAVLJACA_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stavke_fakture",
                        to="app.proizvoddobavljaca",
                    ),
                ),
            ],
            options={
                "db_table": "stavka_fakture",
            },
        ),
        migrations.CreateModel(
            name="Temperatura",
            fields=[
                ("sifra_tm", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vrednost_tp",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Temperatura u Celzijusima",
                        max_digits=5,
                    ),
                ),
                ("vreme_merenja_tp", models.DateTimeField(auto_now_add=True)),
                (
                    "skladiste",
                    models.ForeignKey(
                        db_column="SKLADISTE_sifra_sk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature",
                        to="app.skladiste",
                    ),
                ),
            ],
            options={
                "db_table": "temperatura",
            },
        ),
        migrations.CreateModel(
            name="Transakcija",
            fields=[
                ("sifra_t", models.AutoField(primary_key=True, serialize=False)),
                ("datum_t", models.DateTimeField(auto_now_add=True)),
                ("broj_potvrde_t", models.CharField(max_length=100, unique=True)),
                (
                    "status_t",
                    models.CharField(
                        choices=[
                            ("na_cekanju", "Na čekanju"),
                            ("uspesna", "Uspešna"),
                            ("neuspesna", "Neuspešna"),
                        ],
                        default="na_cekanju",
                        max_length=30,
                    ),
                ),
                (
                    "iznos_t",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "faktura",
                    models.ForeignKey(
                        db_column="FAKTURA_sifra_f",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transakcije",
                        to="app.faktura",
                    ),
                ),
            ],
            options={
                "db_table": "transakcija",
            },
        ),
        migrations.CreateModel(
            name="Ugovor",
            fields=[
                ("sifra_u", models.AutoField(primary_key=True, serialize=False)),
                ("datum_potpisa_u", models.DateField()),
                ("datum_isteka_u", models.DateField()),
                (
                    "status_u",
                    models.CharField(
                        choices=[
                            ("u_pripremi", "U pripremi"),
                            ("aktivan", "Aktivan"),
                            ("istekao", "Istekao"),
                            ("raskinut", "Raskinut"),
                        ],
                        default="aktivan",
                        max_length=30,
                    ),
                ),
                ("uslovi_u", models.TextField()),
                (
                    "dobavljac",
                    models.ForeignKey(
                        db_column="DOBAVLJAC_sifra_db",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ugovori",
                        to="app.dobavljac",
                    ),
                ),
            ],
            options={
                "db_table": "ugovor",
            },
        ),
        migrations.CreateModel(
            name="PredmetIzvestaja",
            fields=[
                ("sifra_pi", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tip_predmeta_pi",
                    models.CharField(
                        choices=[
                            ("DOBAVLJAC", "Dobavljač"),
                            ("FAKTURA", "Faktura"),
                            ("UGOVOR", "Ugovor"),
                            ("PROIZVOD", "Proizvod"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dobavljac",
                    models.ForeignKey(
                        blank=True,
                        db_column="DOBAVLJAC_sifra_db",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.dobavljac",
                    ),
                ),
                (
                    "faktura",
                    models.ForeignKey(
                        blank=True,
                        db_column="FAKTURA_sifra_f",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.faktura",
                    ),
                ),
                (
                    "izvestaj",
                    models.ForeignKey(
                        db_column="IZVESTAJ_sifra_i",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predmeti",
                        to="app.izvestaj",
                    ),
                ),
                (
                    "proizvod",
                    models.ForeignKey(
                        blank=True,
                        db_column="PROIZVOD_sifra_pr",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.proizvod",
                    ),
                ),
                (
                    "ugovor",
                    models.ForeignKey(
                        blank=True,
                        db_column="UGOVOR_sifra_u",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.ugovor",
                    ),
                ),
            ],
            options={
                "db_table": "predmet_izvestaja",
            },
        ),
        migrations.CreateModel(
            name="Penal",
            fields=[
                ("sifra_p", models.AutoField(primary_key=True, serialize=False)),
                ("razlog_p", models.CharField(max_length=500)),
                ("iznos_p", models.DecimalField(decimal_places=2, max_digits=12)),
                ("datum_p", models.DateField(auto_now_add=True)),
                (
                    "tip_penala_p",
                    models.CharField(
                        choices=[
                            ("KASNJENJE_ISPORUKE", "Kašnjenje isporuke"),
                            ("KASNJENJE_PLACANJA", "Kašnjenje plaćanja"),
                            ("KVALITET", "Kvalitet"),
                            ("OSTALO", "Ostalo"),
                        ],
                        default="OSTALO",
                        max_length=30,
                    ),
                ),
                (
                    "ugovor",
                    models.ForeignKey(
                        db_column="UGOVOR_sifra_u",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penali",
                        to="app.ugovor",
                    ),
                ),
            ],
            options={
                "db_table": "penal",
            },
        ),
        migrations.AddField(
            model_name="faktura",
            name="ugovor",
            field=models.ForeignKey(
                db_column="UGOVOR_sifra_u",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fakture",
                to="app.ugovor",
            ),
        ),
        migrations.CreateModel(
            name="Upozorenje",
            fields=[
                ("sifra_u", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("odstupanje", "odstupanje od rute"),
                            ("temperatura", "temperatura"),
                            ("kvar", "kvar vozila"),
                            ("kasnjenje", "kašnjenje utovara"),
                            ("servis", "servis vozila"),
                        ],
                        max_length=50,
                    ),
                ),
                ("poruka", models.TextField()),
                ("vreme", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "isporuka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.isporuka"
                    ),
                ),
            ],
            options={
                "db_table": "upozorenje",
            },
        ),
        migrations.CreateModel(
            name="Servis",
            fields=[
                ("sifra_s", models.AutoField(primary_key=True, serialize=False)),
                ("datum_servisa", models.DateField()),
                ("napomena", models.TextField()),
                (
                    "vrsta",
                    models.CharField(
                        choices=[
                            ("mali", "Mali"),
                            ("veliki", "Veliki"),
                            ("hitan", "Hitan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vozilo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.vozilo"
                    ),
                ),
            ],
            options={
                "db_table": "servis",
            },
        ),
        migrations.CreateModel(
            name="voziloOmogucavaTemperatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vreme", models.DateTimeField(auto_now_add=True)),
                ("vrednost", models.DecimalField(decimal_places=2, max_digits=5)),
                ("min_granica", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_granica", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "isporuka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.isporuka"
                    ),
                ),
                (
                    "sifra_temp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.temperatura",
                    ),
                ),
                (
                    "sifra_vozila",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.vozilo"
                    ),
                ),
            ],
            options={
                "db_table": "temperaturaVozilo",
            },
        ),
        migrations.CreateModel(
            name="Zalihe",
            fields=[
                ("sifra_z", models.AutoField(primary_key=True, serialize=False)),
                (
                    "trenutna_kol_z",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("datum_azuriranja_z", models.DateTimeField(auto_now=True)),
                (
                    "artikal",
                    models.ForeignKey(
                        db_column="ARTIKAL_sifra_a",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zalihe",
                        to="app.artikal",
                    ),
                ),
                (
                    "skladiste",
                    models.ForeignKey(
                        db_column="SKLADISTE_sifra_sk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zalihe",
                        to="app.skladiste",
                    ),
                ),
            ],
            options={
                "db_table": "zalihe",
            },
        ),
        migrations.AddField(
            model_name="kontrolnatabla",
            name="finansijski_analiticari",
            field=models.ManyToManyField(
                blank=True,
                related_name="kontrolne_table",
                through="app.Kreiranje",
                to="app.finansijskianaliticar",
            ),
        ),
        migrations.CreateModel(
            name="Reklamacija",
            fields=[
                ("sifra_r", models.AutoField(primary_key=True, serialize=False)),
                ("datum_prijema_r", models.DateField(auto_now_add=True)),
                (
                    "status_r",
                    models.CharField(
                        choices=[
                            ("prijem", "Prijem"),
                            ("analiza", "Analiza"),
                            ("odgovor", "Odgovor"),
                            ("zatvaranje", "Zatvaranje"),
                        ],
                        default="prijem",
                        max_length=30,
                    ),
                ),
                ("opis_problema_r", models.TextField()),
                (
                    "vreme_trajanja_r",
                    models.IntegerField(help_text="Vreme trajanja u danima"),
                ),
                (
                    "jacina_zalbe_r",
                    models.IntegerField(
                        help_text="Jačina žalbe na skali 1-10",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "dobavljac",
                    models.ForeignKey(
                        db_column="DOBAVLJAC_sifra_db",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reklamacije",
                        to="app.dobavljac",
                    ),
                ),
                (
                    "kontrolor",
                    models.ForeignKey(
                        db_column="KONTROLOR_KVALITETA_sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reklamacije",
                        to="app.kontrolorkvaliteta",
                    ),
                ),
            ],
            options={
                "db_table": "reklamacija",
            },
        ),
        migrations.CreateModel(
            name="Poseta",
            fields=[
                ("sifra_po", models.AutoField(primary_key=True, serialize=False)),
                ("datum_od_po", models.DateTimeField()),
                ("datum_do_po", models.DateTimeField(blank=True, null=True)),
                (
                    "status_po",
                    models.CharField(
                        choices=[
                            ("zakazana", "Zakazana"),
                            ("u_toku", "U toku"),
                            ("zavrsena", "Završena"),
                            ("otkazana", "Otkazana"),
                        ],
                        default="zakazana",
                        max_length=30,
                    ),
                ),
                (
                    "dobavljac",
                    models.ForeignKey(
                        db_column="DOBAVLJAC_sifra_db",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posete",
                        to="app.dobavljac",
                    ),
                ),
                (
                    "kontrolor",
                    models.ForeignKey(
                        db_column="KONTROLOR_KVALITETA_sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posete",
                        to="app.kontrolorkvaliteta",
                    ),
                ),
            ],
            options={
                "db_table": "poseta",
            },
        ),
        migrations.CreateModel(
            name="SeBavi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum_dodele", models.DateTimeField(auto_now_add=True)),
                (
                    "artikal",
                    models.ForeignKey(
                        db_column="ARTIKAL_sifra_a",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.artikal",
                    ),
                ),
                (
                    "skladisni_operater",
                    models.ForeignKey(
                        db_column="SKLADISNI_OPERATOR_sifra_k",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.skladisnioperater",
                    ),
                ),
            ],
            options={
                "db_table": "se_bavi",
            },
        ),
        migrations.AddField(
            model_name="artikal",
            name="skladisni_operateri",
            field=models.ManyToManyField(
                blank=True,
                related_name="artikli",
                through="app.SeBavi",
                to="app.skladisnioperater",
            ),
        ),
        migrations.AddIndex(
            model_name="izvestaj",
            index=models.Index(
                fields=["tip_i", "datum_i"], name="izvestaj_tip_i_383372_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="izvestaj",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period_od_i__isnull", True),
                    ("period_do_i__isnull", True),
                    ("period_do_i__gte", models.F("period_od_i")),
                    _connector="OR",
                ),
                name="ck_izvestaj_period_do_posle_od",
            ),
        ),
        migrations.AddConstraint(
            model_name="merenje",
            constraint=models.UniqueConstraint(
                fields=("kontrolna_tabla", "metrika", "vreme_merenja_me"),
                name="uq_merenje_tabla_metrika_vreme",
            ),
        ),
        migrations.AddConstraint(
            model_name="ocenadobavljaca",
            constraint=models.UniqueConstraint(
                fields=("dobavljac", "kriterijum_od", "period_od_od"),
                name="uq_ocena_dobavljac_kriterijum_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="ocenadobavljaca",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_do_od__gte", models.F("period_od_od"))),
                name="ck_ocena_period_do_posle_od",
            ),
        ),
        migrations.AddConstraint(
            model_name="ocenadobavljaca",
            constraint=models.CheckConstraint(
                condition=models.Q(("datum_ocenj_od__gte", models.F("period_do_od"))),
                name="ck_ocena_datum_posle_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="proizvoddobavljaca",
            constraint=models.UniqueConstraint(
                fields=("dobavljac", "proizvod"), name="uq_proizvod_dobavljaca"
            ),
        ),
        migrations.AddConstraint(
            model_name="cenovnik",
            constraint=models.UniqueConstraint(
                fields=("proizvod_dobavljaca", "datum_od_c"),
                name="uq_cenovnik_pd_datum_od",
            ),
        ),
        migrations.AddConstraint(
            model_name="cenovnik",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("datum_do_c__isnull", True),
                    ("datum_do_c__gte", models.F("datum_od_c")),
                    _connector="OR",
                ),
                name="ck_cenovnik_datum_do_posle_od",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seprimenjuje",
            unique_together={("artikal", "popust")},
        ),
        migrations.AlterUniqueTogether(
            name="sesalje",
            unique_together={("korisnik", "notifikacija")},
        ),
        migrations.AddConstraint(
            model_name="predmetizvestaja",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("dobavljac__isnull", False),
                        ("faktura__isnull", True),
                        ("proizvod__isnull", True),
                        ("ugovor__isnull", True),
                    ),
                    models.Q(
                        ("dobavljac__isnull", True),
                        ("faktura__isnull", False),
                        ("proizvod__isnull", True),
                        ("ugovor__isnull", True),
                    ),
                    models.Q(
                        ("dobavljac__isnull", True),
                        ("faktura__isnull", True),
                        ("proizvod__isnull", True),
                        ("ugovor__isnull", False),
                    ),
                    models.Q(
                        ("dobavljac__isnull", True),
                        ("faktura__isnull", True),
                        ("proizvod__isnull", False),
                        ("ugovor__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_predmet_izvestaja_tacno_jedan_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="kreiranje",
            constraint=models.UniqueConstraint(
                fields=("finansijski_analiticar", "kontrolna_tabla"),
                name="uq_kreiranje_fa_tabla",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sebavi",
            unique_together={("skladisni_operater", "artikal")},
        ),
    ]
