# Generated by Django 5.1.2 on 2025-10-07 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('sifra_r', models.AutoField(primary_key=True, serialize=False)),
                ('polazna_tacka', models.CharField(max_length=100)),
                ('odrediste', models.CharField(max_length=100)),
                ('duzina_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vreme_dolaska', models.DurationField()),
                ('status', models.CharField(choices=[('planirana', 'Planirana'), ('zavrsena', 'Zavrsena'), ('u_toku', 'U toku'), ('odstupanje', 'Odstupanje od pocetne rute')], max_length=20)),
            ],
            options={
                'db_table': 'ruta',
            },
        ),
        migrations.CreateModel(
            name='Vozilo',
            fields=[
                ('sifra_v', models.AutoField(primary_key=True, serialize=False)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('registracija', models.DateTimeField(auto_now_add=True)),
                ('kapacitet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('zauzeto', 'Zauzeto'), ('slobodno', 'Slobodno'), ('u_kvaru', 'U kvaru'), ('na_servisu', 'Na servisu')], default='aktivno', max_length=20)),
            ],
            options={
                'db_table': 'vozilo',
            },
        ),
        migrations.CreateModel(
            name='Isporuka',
            fields=[
                ('sifra_i', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('aktivna_nova', 'Aktivna - Nova'), ('u_toku', 'U toku'), ('spremna', 'Spremna'), ('zavrsena', 'Završena')], default='aktivna_nova', max_length=20)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('datum_polaska', models.DateTimeField(blank=True, null=True)),
                ('rok_is', models.DateTimeField(blank=True, null=True)),
                ('vozac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vozac_isporuke', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ruta')),
                ('vozilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vozilo')),
            ],
            options={
                'db_table': 'isporuka',
            },
        ),
        migrations.CreateModel(
            name='Upozorenje',
            fields=[
                ('sifra_u', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.CharField(choices=[('odstupanje', 'odstupanje od rute'), ('temperatura', 'temperatura'), ('kvar', 'kvar vozila'), ('kasnjenje', 'kašnjenje utovara'), ('servis', 'servis vozila')], max_length=50)),
                ('poruka', models.TextField()),
                ('vreme', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('isporuka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.isporuka')),
            ],
            options={
                'db_table': 'upozorenje',
            },
        ),
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('sifra_s', models.AutoField(primary_key=True, serialize=False)),
                ('datum_servisa', models.DateField()),
                ('napomena', models.TextField()),
                ('vrsta', models.CharField(choices=[('mali', 'Mali'), ('veliki', 'Veliki'), ('hitan', 'Hitan')], max_length=20)),
                ('vozilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vozilo')),
            ],
            options={
                'db_table': 'servis',
            },
        ),
        migrations.CreateModel(
            name='voziloOmogucavaTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme', models.DateTimeField(auto_now_add=True)),
                ('vrednost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_granica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_granica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isporuka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.isporuka')),
                ('sifra_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temperatura')),
                ('sifra_vozila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vozilo')),
            ],
            options={
                'db_table': 'temperaturaVozilo',
            },
        ),
    ]
