# Generated by Django 5.1.2 on 2026-08-29 14:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Racun",
            fields=[
                ("sifra_r", models.AutoField(primary_key=True, serialize=False)),
                ("broj_racuna_r", models.CharField(max_length=34, unique=True)),
                ("naziv_r", models.CharField(max_length=150)),
                (
                    "stanje_r",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "valuta",
                    models.ForeignKey(
                        db_column="JEDINICA_MERE_sifra_jm",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="racuni",
                        to="app.jedinicamere",
                    ),
                ),
            ],
            options={
                "db_table": "racun",
            },
        ),
        migrations.AddField(
            model_name="transakcija",
            name="racun",
            field=models.ForeignKey(
                db_column="RACUN_sifra_r",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transakcije",
                to="app.racun",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="racun",
            constraint=models.CheckConstraint(
                condition=models.Q(("stanje_r__gte", 0)),
                name="ck_racun_stanje_nenegativno",
            ),
        ),
    ]
