# Generated by Django 5.1.2 on 2025-09-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_artikal_dobavljac_faktura_kategorijaproizvoda_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ime_k",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="lozinka_k",
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="mail_k",
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="prz_k",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="tip_k",
            field=models.CharField(
                choices=[
                    ("logisticki_koordinator", "Logistički koordinator"),
                    ("skladisni_operater", "Skladišni operater"),
                    ("nabavni_menadzer", "Nabavni menadžer"),
                    ("finansijski_analiticar", "Finansijski analitičar"),
                    ("kontrolor_kvaliteta", "Kontrolor kvaliteta"),
                    ("administrator", "Administrator"),
                ],
                default=None,
                max_length=30,
            ),
        ),
    ]
