# Generated by Django 5.1.2 on 2025-10-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ruta_vozilo_isporuka_upozorenje_servis_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zalihe',
            unique_together=set(),
        ),
    ]
