# Generated by Django 5.1.2 on 2025-10-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ruta_vozilo_isporuka_upozorenje_servis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vozac',
            fields=[
                ('sifra_vo', models.AutoField(primary_key=True, serialize=False)),
                ('ime_vo', models.CharField(max_length=100)),
                ('prz_vo', models.CharField(max_length=100)),
                ('br_voznji', models.IntegerField()),
                ('status', models.CharField(choices=[('slobodan', 'Slobodan'), ('zauzet', 'Zauzet'), ('na_odmoru', 'Na odmoru')], default='slobodan', max_length=20)),
            ],
            options={
                'db_table': 'vozac',
            },
        ),
    ]
