# Generated by Django 5.1.2 on 2025-10-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_ruta_vozilo_isporuka_upozorenje_servis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="izvestaj",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="izvestaji_pdfs/"),
        ),
    ]
