# Generated by Django 5.1.2 on 2025-10-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vozac'),
    ]

    operations = [
        migrations.AddField(
            model_name='isporuka',
            name='kolicina_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='isporuka',
            name='status',
            field=models.CharField(choices=[('aktivna', 'Nova'), ('u_toku', 'U toku'), ('spremna', 'Spremna'), ('zavrsena', 'Završena')], default='aktivna_nova', max_length=20),
        ),
        migrations.AlterField(
            model_name='vozilo',
            name='registracija',
            field=models.DateField(blank=True),
        ),
    ]
