# Generated by Django 5.1.2 on 2025-10-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_zalihe_unique_together"),
        ("app", "0003_izvestaj_pdf_file"),
    ]

    operations = []
