# Generated by Django 5.1.2 on 2025-10-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_zalihe_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='vreme_merenja',
            field=models.DateTimeField(),
        ),
    ]
