# Generated by Django 5.1.2 on 2025-10-10 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_isporuka_kolicina_kg_alter_isporuka_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isporuka',
            name='status',
            field=models.CharField(choices=[('aktivna', 'Nova'), ('u_toku', 'U toku'), ('spremna', 'Spremna'), ('zavrsena', 'Završena')], default='aktivna', max_length=20),
        ),
        migrations.AlterField(
            model_name='isporuka',
            name='vozac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vozac_isporuke', to='app.vozac'),
        ),
    ]
