# Generated by Django 5.1.2 on 2025-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_isporuka_status_alter_isporuka_vozac'),
    ]

    operations = [
        migrations.AddField(
            model_name='isporuka',
            name='datum_dolaska',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
