# Generated by Django 5.1.2 on 2025-10-11 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_isporuka_datum_dolaska'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isporuka',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ruta'),
        ),
        migrations.AlterField(
            model_name='isporuka',
            name='vozac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vozac_isporuke', to='app.vozac'),
        ),
        migrations.AlterField(
            model_name='isporuka',
            name='vozilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vozilo'),
        ),
    ]
