# Generated by Django 5.1.2 on 2025-10-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_isporuka_ruta_alter_isporuka_vozac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isporuka',
            name='vozac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vozac'),
        ),
    ]
