# Generated by Django 5.1.2 on 2025-10-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20251011_0837'),
        ('app', '0008_alter_isporuka_vozac'),
    ]

    operations = [
    ]
