# Generated by Django 5.1.2 on 2026-04-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_merge_20251018_2238"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboard",
            options={"ordering": ["-datum_d"]},
        ),
        migrations.RemoveField(
            model_name="dashboard",
            name="nabavni_menadzer",
        ),
        migrations.RemoveField(
            model_name="dashboard",
            name="skladisni_operater",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="period_do_d",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="period_od_d",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="snimak_metrika_json",
            field=models.TextField(
                default="{}",
                help_text="JSON snimak metrika dashboarda za izabrani period.",
            ),
        ),
        migrations.AddField(
            model_name="izvestaj",
            name="dashboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="izvestaji",
                to="app.dashboard",
            ),
        ),
        migrations.AddField(
            model_name="izvestaj",
            name="dobavljaci",
            field=models.ManyToManyField(
                blank=True, related_name="izvestaji", to="app.dobavljac"
            ),
        ),
        migrations.AddField(
            model_name="izvestaj",
            name="fakture",
            field=models.ManyToManyField(
                blank=True, related_name="izvestaji", to="app.faktura"
            ),
        ),
        migrations.AddField(
            model_name="izvestaj",
            name="penali",
            field=models.ManyToManyField(
                blank=True, related_name="izvestaji", to="app.penal"
            ),
        ),
        migrations.AddField(
            model_name="izvestaj",
            name="period_do_i",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="izvestaj",
            name="period_od_i",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="finansijski_analiticar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboards",
                to="app.finansijskianaliticar",
            ),
        ),
        migrations.AlterField(
            model_name="izvestaj",
            name="sadrzaj_i",
            field=models.TextField(blank=True, default="{}"),
        ),
        migrations.AlterField(
            model_name="izvestaj",
            name="tip_i",
            field=models.CharField(
                choices=[
                    ("zalihe", "Izveštaj o zalihama"),
                    ("finansijski", "Finansijski izveštaj"),
                    ("fakture", "Izveštaj o fakturama"),
                    ("penali", "Izveštaj o penalima"),
                    ("fa_troskovi_profitabilnost", "FA troškovi i profitabilnost"),
                    ("dobavljaci", "Izveštaj o dobavljačima"),
                    ("kvalitet", "Izveštaj o kvalitetu"),
                    ("temperature", "Izveštaj o temperaturama"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="izvestaj",
            index=models.Index(
                fields=["tip_i", "datum_i"], name="izvestaj_tip_i_383372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="izvestaj",
            index=models.Index(
                fields=["kreirao", "datum_i"], name="izvestaj_kreirao_1faef7_idx"
            ),
        ),
    ]
