# Generated by Django 5.1.2 on 2025-10-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20251018_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rampa',
            fields=[
                ('sifra_rp', models.AutoField(primary_key=True, serialize=False)),
                ('oznaka', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('slobodna', 'Slobodna'), ('zauzeta', 'Zauzeta'), ('u_servisu', 'U servisu')], default='slobodna', max_length=20)),
                ('skladiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rampe', to='app.skladiste')),
            ],
            options={
                'db_table': 'rampa',
            },
        ),
        migrations.CreateModel(
            name='TerminUtovara',
            fields=[
                ('sifra_tu', models.AutoField(primary_key=True, serialize=False)),
                ('vreme_pocetka', models.DateTimeField()),
                ('vreme_zavrsetka', models.DateTimeField()),
                ('vreme_utovara', models.DurationField(blank=True, help_text='Trajanje utovara u satima', null=True)),
                ('potvrda_operatera', models.BooleanField(default=False)),
                ('isporuka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termin_utovara', to='app.isporuka')),
                ('operater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.skladisnioperater')),
                ('rampa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rampa')),
                ('skladiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skladiste')),
                ('vozilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vozilo')),
            ],
            options={
                'db_table': 'termin_utovara',
            },
        ),
    ]
