# Generated by Django 5.1.2 on 2025-10-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20251018_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatura',
            name='vozilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='app.vozilo'),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='skladiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='app.skladiste'),
        ),
    ]
