# Generated by Django 5.1.2 on 2026-04-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_dashboard_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="izvestaj",
            name="penali",
        ),
    ]
