# Generated by Django 5.1.2 on 2025-10-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rampa_terminutovara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rampa',
            name='status',
            field=models.CharField(choices=[('slobodna', 'Slobodna'), ('zauzeta', 'Zauzeta')], default='slobodna', max_length=20),
        ),
    ]
