# Generated by Django 5.1.2 on 2025-10-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_rampa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izvestaj',
            name='tip_i',
            field=models.CharField(choices=[('zalihe', 'Izveštaj o zalihama'), ('finansijski', 'Finansijski izveštaj'), ('dobavljaci', 'Izveštaj o dobavljačima'), ('kvalitet', 'Izveštaj o kvalitetu'), ('temperature', 'Izveštaj o temperaturama'), ('koordinator', 'Izveštaj logističkog koordinatora')], max_length=30),
        ),
    ]
