# Generated by Django 5.1.2 on 2025-10-23 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_izvestaj_tip_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izvestaj',
            old_name='sifra_i',
            new_name='sifra_iz',
        ),
        migrations.CreateModel(
            name='Voznja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trenutna_lat', models.FloatField()),
                ('trenutna_lon', models.FloatField()),
                ('vreme_azuriranja', models.DateTimeField(auto_now=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ruta')),
            ],
            options={
                'db_table': 'voznja',
            },
        ),
    ]
