services:
  neo4j:
    image: neo4j:5.9
    container_name: supplier_neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - supplier_network
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null -q http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  supplier-analysis-ms:
    build: .
    container_name: supplier-analysis-ms
    ports:
      - "8001:8001"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - DJANGO_SERVICE_URL=http://host.docker.internal:8000
      - DEBUG=true
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - supplier_network

networks:
  supplier_network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
